### ISSUE TITLE
Try to give full info about what you are giving

### ISSUE THREAD

**Issue by Praharsh1109** [kgdunn/python-basic-notebooks#1]
In this, you have just mentioned what to do. so for the beginner, this is not good enough so you can put the data like what is not good in it. and whats the benefits of it in the future.

**Comment by Praharsh1109** [comment]
sorry to interrupt like this.

**Comment by kgdunn** [comment]
I'm not sure what file in the repo this issue is related to. 
No problem about interrupting. It is also not something that I can solve here though.
